name: ShellCheck

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          # Specify additional files to check, using a glob pattern that works
          additional_files: 'scripts/*.sh' # Ensure you have shell scripts in this directory
          
          # Optional: Paths to ignore when running ShellCheck
          ignore_paths: '' # Leave empty or specify paths to ignore
          
          # Optional: Names to ignore when running ShellCheck
          ignore_names: main
          
          # Minimum severity of errors to consider. Options: [error, warning, info, style]
          severity: 'style' # Default is 'style'
          
          # Run shellcheck on _all_ files at once, instead of one at a time
          check_together: 'false' # Default is 'false'
          
          # Directory to be searched for files. Defaults to '.'
          scandir: '.' # Default is '.'
          
          # Output format (checkstyle, diff, gcc, json, json1, quiet, tty)
          format: 'gcc' # Default is 'gcc'
          
          # Specify a concrete version of ShellCheck to use
          version: 'stable' # Default is 'stable'
